### ISSUE TITLE
Web GUI for easier management

### ISSUE THREAD

**Issue by robsd** [torch2424/live-stream-radio#108]
This is a great project and I'm not sure if this is pushing it but it would be so cool if this project has a web-based GUI to manage the stream audio and video files as well as start and stop the stream. Configurable Wi-Fi options would also be cool. I have been using Volumio quite a lot and something like that would be so cool for this project!

**Comment by AndreasWebdev** [comment]
The api is capable of doing exactly that if you want to implement your own web ui. Otherwise there are multiple projects in the works, some feature a web ui and some a desktop-like experience, made by other users.

**Comment by robsd** [comment]
Ah ok cool, do you have any links the projects? Would love to check them out

**Comment by torch2424** [comment]
@AndreasWebdev Actually has a project here to wrap around the API: https://github.com/LSRemote/lsr-wrapper

And was working on a very beautiful web gui a while back for this 😄

**Comment by torch2424** [comment]
Also, see #109 ! 😄

**Comment by AndreasWebdev** [comment]
I'll close this issue for clarity, feel free to reopen it if you have any more questions :)
