### ISSUE TITLE
Very Simple (i mean very very simple) Control Panel 

### ISSUE THREAD

**Issue by Tresmos** [torch2424/live-stream-radio#109]
idk if its worth adding it to the readme but i've made a simple web panel using my little knowledge about this stuff for live-stream-radio if anyone wants to use it.
https://github.com/Tresmos/live-stream-radio-cp

Any feature requests are welcome but not guaranteed. Pls PR thanks 😁

**Comment by torch2424** [comment]
Oh this is so cool! Thanks for adding this! Yeah definitely this is worth adding to the project. Glad to see other people getting behind the project 😄

**Comment by AndreasWebdev** [comment]
I'll close this issue for clarity, feel free to reopen it if you have any more questions :)
