### ISSUE TITLE
After attempting to start the stream I get an error with ffmpeg

### ISSUE THREAD

**Issue by ALegitCookie** [torch2424/live-stream-radio#120]
Error: ffmpeg exited with code 1: Error initializing complex filters.
Invalid argument

    at ChildProcess.<anonymous> (/home/pi/.config/versions/node/v10.15.3/lib/node_modules/live-stream-radio/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

This is on a Raspi 3 Model B+ with Raspbian Stretch. Completely updated. Any help? I don't nknow what any of this means.

**Comment by ALegitCookie** [comment]
I'm also getting this error sometimes too:

(node:26654) UnhandledPromiseRejectionWarning: Error: Error in file: /tmp/live-stream-radio-gif-with-pal-1553789624949.gif

spawn /home/pi/.config/versions/node/v10.15.3/lib/node_modules/live-stream-radio/node_modules/gifsicle/vendor/gifsicle ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:26654) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:26654) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by torch2424** [comment]
Helllo!

So it seems like your FFMPEG is not compiled with all the required libraries. See the [Getting Started](https://torch2424.github.io/live-stream-radio/#/cli/getting-started) in the documentation for either compiling FFMPEG, or downloading a prebuilt FFMPEG with the libraries.

Let me know if that helps! Thanks! 😄

**Comment by ALegitCookie** [comment]
I downloaded the pre-built ffmpeg you provided, but I'm not sure how to install it. The readme and the Install guide provided are very confusing. I'm quite new to this. Is there a place I could find a guide on how to install it?

**Comment by ALegitCookie** [comment]
I'm not getting any ffmpeg errors anymore, just stuff about node.js and gifs (look at my above comment where I pasted the second error i've been getting)

**Comment by AndreasWebdev** [comment]
`gifsicle ENOENT`

Are you sure you have gifsicle installed propertly? The nodeJS error says it can't find it.

**Comment by torch2424** [comment]
@ALegitCookie Ah,

Well you have in your output logs that you have: `Error: ffmpeg exited with code 1: Error initializing complex filters.`. Which is a sign the FFMPEG isn't working.

I'd suggest looking over the [Getting Started](https://torch2424.github.io/live-stream-radio/#/cli/getting-started) guide like I mentioned. It does take a bit of linux / node "know how" to get the project going. So perhaps playing around with an older project, or trying the [initial 1.0 of this project which may be easier for you](https://github.com/torch2424/live-stream-radio/tree/e4d0a6c3ad95cf898c2fc5343bb7ff6ff6c0dddd). Or even some guides on SSH'ing around raspberry pis, or some really simple "introduction to nodejs" may help.

Let me know if this helps 😄 Thank you! 👍

**Comment by AndreasWebdev** [comment]
I'll close this issue for clarity, feel free to reopen it if you have any more questions :)
