### ISSUE TITLE
RPI 3b+ : exact install explanation

### ISSUE THREAD

**Issue by ar82249728** [torch2424/live-stream-radio#123]
Hello,

I used the previous script of piStreamRadio.
All worked good on my RPI3b+.
I don't understand the new files of piStreamRadio.

QUESTIONS : 

1. Can someone give me the exact sequence of command line to install the new piStreamRadio on Raspberry pi ?

2. Where can I download and install the previous version of piStreamRadio ?

Thank for your help !

**Comment by torch2424** [comment]
Hello!

So the new `piStreamRadio` depends on node, and honestly, makes it a more complex project to get up and running, but it has much more features / fine grain control. [Head over to the documentation if you want to try it out](https://torch2424.github.io/live-stream-radio/#/).

But if you just want to use the old piStreamRadio, here is the [last old piStreamRadio Release](https://github.com/torch2424/live-stream-radio/releases/tag/1.2.0) and it's [source code](https://github.com/torch2424/live-stream-radio/tree/1.2.0). 😄 

Let me know if this helps! Thanks!

**Comment by ar82249728** [comment]
@torch2424 Thank you for your answer.

As I'm not enough qualified to use the new script, I will try to use the previous thanks to your linK.
Thanks a lot ! :)

**Comment by torch2424** [comment]
@ar82249728 You are welcome! 😄 

I'll go ahead and close this issue. Feel free to reopen this if you need anything else! 👍
