### ISSUE TITLE
Best config settings?

### ISSUE THREAD

**Issue by between2d** [torch2424/live-stream-radio#124]
Hi! 
Using the default settings, the stream was working ok, albeit with classic youtube error of "Stream is not optimized". When I changed the settings to 1280x720, I started getting this ffmpeg error after a couple seconds of streaming: 

> error: ffmpeg was killed with signal SIGKILL
> 	 at ChildProcess.<anonymous> (/home/rieg/.nvm/versions/node/v12.1.0/lib/node_modules/live-stream-radio/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
> 	at ChildProcess.emit (events.js:196:13)
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
> 
> ffmpeg encountered an error.
> Please see the stderror output above to fix the issue.

I saw in another thread ( #120 ) that updating ffmpeg would help. I updated it and specified the path in the config.json file, but I'm still getting the same error. 

Here is my config.json 

> "stream_url": "rtmp://a.rtmp.youtube.com/live2/$stream_key",
>   "stream_key": "(duh)",
>   "ffmpeg_path": "/usr/bin/ffmpeg",
>   "video_codec": "libx264",
>   "audio_codec": "aac",
>   "audio_bit_rate": "128k",
>   "audio_sample_rate": "44100",
>   "normalize_audio": true,
>   "video_height": "720",
>   "video_width": "1280",
>   "video_bit_rate": "2500k",
>   "video_fps": "24",
>   "bufsize": "960k",
>   "crf": "28",
>   "preset": "superfast",
>   "threads": 2,
>   "max_gif_size": "720",
> 

Any ideas?

**Comment by torch2424** [comment]
@between2d So in my opinion, the settings are kinda subjective, and really hit or miss depending on your stream and things. I say just trial and error to test what works for you.

My apologies for not having a definitive answer. I found that the default settings tend to be a good "one size fits all" with alright performance, but we can keep this issue open for discussion and sharing configs 😄

**Comment by between2d** [comment]
I tried going back to the original config and I'm still stuck with 

> > error: ffmpeg was killed with signal SIGKILL
> at ChildProcess. (/home/rieg/.nvm/versions/node/v12.1.0/lib/node_modules/live-stream-radio/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
> at ChildProcess.emit (events.js:196:13)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
> 
> ffmpeg encountered an error.
> Please see the stderror output above to fix the issue.

Could it be a problem with fluent-ffmpeg?

**Comment by AndreasWebdev** [comment]
ffmpeg getting killed with a SIGKILL is always something your operating system does. From a short google on similar issues, it seems that the system terminates FFMPEG if it's too memory-consuming. Could you try to stream and watch your server's statistics (cpu usage, ram usage etc)?

**Comment by between2d** [comment]
> ffmpeg getting killed with a SIGKILL is always something your operating system does. From a short google on similar issues, it seems that the system terminates FFMPEG if it's too memory-consuming. Could you try to stream and watch your server's statistics (cpu usage, ram usage etc)?

You're right! I removed some bloat and GUI and now it was running smoothly! Thanks!
