### ISSUE TITLE
ffmpeg videooutput error

### ISSUE THREAD

**Issue by between2d** [torch2424/live-stream-radio#125]
Hi again! 
I'm still learning, but with this error, I don't even know what to look for, hahah. Can anyone help me out?

> Starting stream! 🛠️
> 
> 
> Streaming to: (yeah)
> 
> 
> Finding audio... 🎤
> 
> 
> Playing the audio:
> /home/joe/.nvm/musak/audio/joeulate/7CLERKS.mp3
> 
> 
> Finding/Optimizing video... 📺
> 
> 
> Playing the video:
> /home/joe/.nvm/musak/video/nestedDirectoriesWork/publicDomainEarth.webm
> 
> 
> Artist: joeulate
> Album: #
> Song: I shouldn't even be here today
> Duration (seconds): 61
> 
> 
> 
> Spawned Ffmpeg with command:
> ffmpeg -stream_loop -1 -i /home/joe/.nvm/musak/video/nestedDirectoriesWork/publicDomainEarth.webm -i /home/joe/.nvm/musak/audio/joeulate/7CLERKS.mp3 -f lavfi -re -i anullsrc -filter_complex [1:a] adelay=3000|3000 [delayedaudio]; [delayedaudio][2:a] amix=inputs=2:duration=first:dropout_transition=3 [audiooutput]; [audiooutput] loudnorm [audiooutput]; [0:v] fps=fps=24, drawtext=text='24/7 Beats':fontfile=/home/joe/.nvm/musak/./fonts/Lato-Regular.ttf:fontsize=(w * 0.03333333333333333):bordercolor=#000000:borderw=1:fontcolor=#FFFFFF:y=(h * 0.05):x=(w * 0),drawtext=text=' joeulate':fontfile=/home/joe/.nvm/musak/./fonts/Lato-Regular.ttf:fontsize=(w * 0.03333333333333333):bordercolor=#000000:borderw=1:fontcolor=#FFFFFF:y=(h * 0.1):x=(w * 0),drawtext=text='Song: I shouldn't even be here today':fontfile=/home/joe/.nvm/musak/./fonts/Lato-Regular.ttf:fontsize=(w * 0.03333333333333333):bordercolor=#000000:borderw=1:fontcolor=#FFFFFF:y=(h * 0.25):x=(w * 0.02) [videooutput] -acodec copy -acodec copy -map [videooutput] -map [audiooutput] -r 24 -g 48 -t 67 -pix_fmt yuv420p -x264-params keyint=48:min-keyint=48:scenecut=-1 -s 854x480 -b:v 500k -b:a 128k -ar 44100 -acodec aac -vcodec libx264 -preset superfast -bufsize 960k -crf 28 -threads 2 -f flv rtmp://a.rtmp.youtube.com/live2/cd2e-2tkv-ed98-259f
> 
> Audio Progress ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | Time Playing: 0s |
> 
> 
> ████████████████████████████████████████████████████████████████████████████████
> 
> 
> ffmpeg stderr:
> 
>  ffmpeg version 4.1.3-0ubuntu1 Copyright (c) 2000-2019 the FFmpeg developers
>   built with gcc 8 (Ubuntu 8.3.0-6ubuntu1)
>   configuration: --prefix=/usr --extra-version=0ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
>   libavutil      56. 22.100 / 56. 22.100
>   libavcodec     58. 35.100 / 58. 35.100
>   libavformat    58. 20.100 / 58. 20.100
>   libavdevice    58.  5.100 / 58.  5.100
>   libavfilter     7. 40.101 /  7. 40.101
>   libavresample   4.  0.  0 /  4.  0.  0
>   libswscale      5.  3.100 /  5.  3.100
>   libswresample   3.  3.100 /  3.  3.100
>   libpostproc    55.  3.100 / 55.  3.100
> Input #0, matroska,webm, from '/home/joe/.nvm/musak/video/nestedDirectoriesWork/publicDomainEarth.webm':
>   Metadata:
>     encoder         : Google
>   Duration: 00:00:24.02, start: 0.000000, bitrate: 661 kb/s
>     Stream #0:0: Video: vp8, yuv420p(progressive), 640x360, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
>     Stream #0:1: Audio: vorbis, 44100 Hz, stereo, fltp (default)
> Input #1, mp3, from '/home/joe/.nvm/musak/audio/joeulate/7CLERKS.mp3':
>   Metadata:
>     title           : I shouldn't even be here today
>     album           : #
>     encoded_by      : dBpoweramp Release 16.5
>     Band            : joeulate
>     track           : #
>     artist          : joeulate
>     album_artist    : joeulate
>     date            : 2019
>   Duration: 00:01:00.02, start: 0.023021, bitrate: 260 kb/s
>     Stream #1:0: Audio: mp3, 48000 Hz, stereo, fltp, 260 kb/s
>     Metadata:
>       encoder         : LAME3.100
> Input #2, lavfi, from 'anullsrc':
>   Duration: N/A, start: 0.000000, bitrate: 705 kb/s
>     Stream #2:0: Audio: pcm_u8, 44100 Hz, stereo, u8, 705 kb/s
> Output with label 'videooutput' does not exist in any defined filter graph, or was already used elsewhere.
> 
> ffmpeg stdout:
> 
> 
> ffmpeg err:
> 
>  Error: ffmpeg exited with code 1: Output with label 'videooutput' does not exist in any defined filter graph, or was already used elsewhere.
> 
>     at ChildProcess.<anonymous> (/home/joe/.nvm/versions/node/v12.1.0/lib/node_modules/live-stream-radio/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
>     at ChildProcess.emit (events.js:196:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
> 
> 
> ffmpeg encountered an error. 😨
> Please see the stderror output above to fix the issue.
>

**Comment by torch2424** [comment]
Hmmm cc @AndreasWebdev As they tend to be good with these 😂 

But our general response is, when it comes to video errors, is you FFMPEG Compiled with all the correct filters and things? That, or perhaps the video has some strange characters in it, and our "safe string" function messed up.

Let me know if that helps! 😄

**Comment by Trackerus** [comment]
> Hi again!
> I'm still learning, but with this error, I don't even know what to look for, hahah. Can anyone help me out?
> 
> > Starting stream! 🛠️
> > Streaming to: (yeah)
> > Finding audio... 🎤
> > Playing the audio:
> > /home/joe/.nvm/musak/audio/joeulate/7CLERKS.mp3
> > Finding/Optimizing video... 📺
> > Playing the video:
> > /home/joe/.nvm/musak/video/nestedDirectoriesWork/publicDomainEarth.webm
> > Artist: joeulate
> > Album: #
> > Song: I shouldn't even be here today
> > Duration (seconds): 61
> > Spawned Ffmpeg with command:
> > ffmpeg -stream_loop -1 -i /home/joe/.nvm/musak/video/nestedDirectoriesWork/publicDomainEarth.webm -i /home/joe/.nvm/musak/audio/joeulate/7CLERKS.mp3 -f lavfi -re -i anullsrc -filter_complex [1:a] adelay=3000|3000 [delayedaudio]; [delayedaudio][2:a] amix=inputs=2:duration=first:dropout_transition=3 [audiooutput]; [audiooutput] loudnorm [audiooutput]; [0:v] fps=fps=24, drawtext=text='24/7 Beats':fontfile=/home/joe/.nvm/musak/./fonts/Lato-Regular.ttf:fontsize=(w * 0.03333333333333333):bordercolor=#000000:borderw=1:fontcolor=#FFFFFF:y=(h * 0.05):x=(w * 0),drawtext=text=' joeulate':fontfile=/home/joe/.nvm/musak/./fonts/Lato-Regular.ttf:fontsize=(w * 0.03333333333333333):bordercolor=#000000:borderw=1:fontcolor=#FFFFFF:y=(h * 0.1):x=(w * 0),drawtext=text='Song: I shouldn't even be here today':fontfile=/home/joe/.nvm/musak/./fonts/Lato-Regular.ttf:fontsize=(w * 0.03333333333333333):bordercolor=#000000:borderw=1:fontcolor=#FFFFFF:y=(h * 0.25):x=(w * 0.02) [videooutput] -acodec copy -acodec copy -map [videooutput] -map [audiooutput] -r 24 -g 48 -t 67 -pix_fmt yuv420p -x264-params keyint=48:min-keyint=48:scenecut=-1 -s 854x480 -b:v 500k -b:a 128k -ar 44100 -acodec aac -vcodec libx264 -preset superfast -bufsize 960k -crf 28 -threads 2 -f flv rtmp://a.rtmp.youtube.com/live2/cd2e-2tkv-ed98-259f
> > Audio Progress ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | Time Playing: 0s |
> > ████████████████████████████████████████████████████████████████████████████████
> > ffmpeg stderr:
> > ffmpeg version 4.1.3-0ubuntu1 Copyright (c) 2000-2019 the FFmpeg developers
> > built with gcc 8 (Ubuntu 8.3.0-6ubuntu1)
> > configuration: --prefix=/usr --extra-version=0ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
> > libavutil      56. 22.100 / 56. 22.100
> > libavcodec     58. 35.100 / 58. 35.100
> > libavformat    58. 20.100 / 58. 20.100
> > libavdevice    58.  5.100 / 58.  5.100
> > libavfilter     7. 40.101 /  7. 40.101
> > libavresample   4.  0.  0 /  4.  0.  0
> > libswscale      5.  3.100 /  5.  3.100
> > libswresample   3.  3.100 /  3.  3.100
> > libpostproc    55.  3.100 / 55.  3.100
> > Input #0, matroska,webm, from '/home/joe/.nvm/musak/video/nestedDirectoriesWork/publicDomainEarth.webm':
> > Metadata:
> > encoder         : Google
> > Duration: 00:00:24.02, start: 0.000000, bitrate: 661 kb/s
> > Stream #0:0: Video: vp8, yuv420p(progressive), 640x360, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
> > Stream #0:1: Audio: vorbis, 44100 Hz, stereo, fltp (default)
> > Input #1, mp3, from '/home/joe/.nvm/musak/audio/joeulate/7CLERKS.mp3':
> > Metadata:
> > title           : I shouldn't even be here today
> > album           : #
> > encoded_by      : dBpoweramp Release 16.5
> > Band            : joeulate
> > track           : #
> > artist          : joeulate
> > album_artist    : joeulate
> > date            : 2019
> > Duration: 00:01:00.02, start: 0.023021, bitrate: 260 kb/s
> > Stream #1:0: Audio: mp3, 48000 Hz, stereo, fltp, 260 kb/s
> > Metadata:
> > encoder         : LAME3.100
> > Input #2, lavfi, from 'anullsrc':
> > Duration: N/A, start: 0.000000, bitrate: 705 kb/s
> > Stream #2:0: Audio: pcm_u8, 44100 Hz, stereo, u8, 705 kb/s
> > Output with label 'videooutput' does not exist in any defined filter graph, or was already used elsewhere.
> > ffmpeg stdout:
> > ffmpeg err:
> > Error: ffmpeg exited with code 1: Output with label 'videooutput' does not exist in any defined filter graph, or was already used elsewhere.
> > ```
> > at ChildProcess.<anonymous> (/home/joe/.nvm/versions/node/v12.1.0/lib/node_modules/live-stream-radio/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
> > at ChildProcess.emit (events.js:196:13)
> > at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
> > ```
> > 
> > 
> > ffmpeg encountered an error. 😨
> > Please see the stderror output above to fix the issue.

Hi, Had the same issue. 
Check your 7CLERKS.mp3 Tags for any special characters.
Especially ' is making problems.
I think this should be addressed in the call itself.
It would be nice to escape this.
Regards, Trackerus.

**Comment by torch2424** [comment]
@Trackerus Thanks for the help! 😄 

@AndreasWebdev Yeah we should 😂 Hopefully I'll find the time sometime soon 👍

**Comment by between2d** [comment]
> My gut is telling me it's the ' as well. We should really fix the escaping 😅

that was exactly it! thanks!
