### ISSUE TITLE
Stream always stopping after 12 hours (youtube)

### ISSUE THREAD

**Issue by between2d** [torch2424/live-stream-radio#126]
Hi again!
I'm noticing that my stream always goes offline after around 12 hours. It gives me this error:

> encoder : LAME 3.100 
> Input #2, lavfi, from '.anullsrc':
>  Duration: N/A, start: 0.000000, bitrate: 705 kb/s 
> Stream #2:0: Audio: pcm_u8, 44100 Hz, stereo, u8, 705 kb/s
> rtmp://a.rtmp.youtube.com/live2/(yeah): Input/output error 
> 
> ffmpeg stdout: 
> 
> ffmpeg err: Error: ffmpeg exited with code 1: rtmp://a.rtmp.youtube.com/live2/(yeah): Input/output error 
> 
> at ChildProcess . <anonymous> (/home/(yeah)/.nvm/versions/node/v12.1.0/lib/node_modules/Iive-stream-radio/node_modules/fluent-ffmpeg/lib/processor.js:182:22) 
> 
> ffmpeg encountered an error. 
> 
> Please see the stderror output above to fix the Issue. 

any ideas?

**Comment by AndreasWebdev** [comment]
Did you get any output from ffmpeg (usually a wall oftext with errors)?

**Comment by torch2424** [comment]
@between2d 

So I did some research in the past, and I can't find the issue I closed that mentioned it. But this is on Youtube's end. They tend to just kill off (by closing the connection for a few seconds) of any long running streams after a while, and it's kind of random when they do it. Personally, my streams can get killed anywhere from like 6 hours, to like 6 days.

Feel free to look through the issues for it, but the original piStreamRadio had this problem as well, and found a discussion of this from some super random ffmpeg forum having the exact same problem :( 

Let me know if this helps! But I think we may want to close this as can't fix. Unless, you have like an experience of something like OBS never getting closed. 🤔 

Thanks! 😄

**Comment by AndreasWebdev** [comment]
My theory is, that YouTube kills off your connection once their servers switch around in their server centers. I know FlareTV (the person who had the 24/7 Pewdiepie vs. T-Series stream which was live from september 2018 till april 2019) had similar problems.

**Comment by AndreasWebdev** [comment]
I'm gonna close this issue due to inactivity (and because of the mentioned thoughts that it might be something on YouTube's end).

Feel free to reopen this issue if you believe this issue happens because of live-stream-radio.
