### ISSUE TITLE
Crash Script?

### ISSUE THREAD

**Issue by dropitlikecross** [torch2424/live-stream-radio#132]
Anyone have a script that restart the live stream if it crashes?

I wrote a dirty one but if someone has something nicer it would be better:

```
trap "kill 0" SIGINT

while :
do
./.nvm/versions/node/v10.16.3/bin/live-stream-radio --start myStream
done

```

**Comment by torch2424** [comment]
So What I usually use is [systemd](https://www.digitalocean.com/community/tutorials/systemd-essentials-working-with-services-units-and-the-journal). You can set this up to run on boot, and automatically run again if it crashes 😄 

Here is my example systemd unit I use for everything: https://github.com/torch2424/dotFiles/blob/master/.files_templates/systemctl.service
