### ISSUE TITLE
Stream stops after each track ends

### ISSUE THREAD

**Issue by dropitlikecross** [torch2424/live-stream-radio#133]
The stream plays 1 song then stop the stream. Restarts and plays the next stream. Anyone have this problem and know of a resolution?

**Comment by torch2424** [comment]
Ahh so this is the sam issue as: https://github.com/torch2424/live-stream-radio/issues/104 We have a discussion ongoing there, and thankfully @StoneCypher Has proposed a solution! I just haven't had the time to try it out (I've been moving and doing other open sourc estuff 😿 )

So I'll close this issue, and feel free to add some suggestions or problems there.

Also, if this is a different issue, feel free to message me back to re-open this 😄
