### ISSUE TITLE
Tracking down a takedown notice

### ISSUE THREAD

**Issue by beamercola** [torch2424/live-stream-radio#140]
Is there any way to track down what track was playing when a takedown happens?  I'm streaming existing youtube videos, but not sure how to remove the offender.  Putting it back live I feel like will just get me a permanent ban.

**Comment by torch2424** [comment]
@beamercola Hello! :smile: 

So unfortunately, we wouldn't have any control of that :( You'd have to see what Youtube, or whatever platform you are using calls out the reason for the takedown.

I wish you the best of luck! :+1:
