### ISSUE TITLE
Running the stream 24/7?

### ISSUE THREAD

**Issue by pawlean** [torch2424/live-stream-radio#165]
Hey folks!

This isn't an issue on live-stream-radio itself (great tool btw!) But more on how you all set it up to run 24/7? I'm trying to use AWS Lightsail (an EC2 instance basically) to get started, but every time I close the terminal through ssh, it just kills the stream. How are you all keeping it running 24/7?

Any insight would be appreciated 😄

**Comment by Tresmos** [comment]
screen might be what you're looking for.
https://linuxize.com/post/how-to-use-linux-screen/

**Comment by pawlean** [comment]
Funnily enough, I discovered screen for another thing. Thank you so much 😊
