### ISSUE TITLE
DISCUSSION: Consider Moving the Project to Node.

### ISSUE THREAD

**Issue by torch2424** [torch2424/live-stream-radio#40]
As fun as building all of this in bash has been, I've been getting tons of errors from users from rand bash errors, and the code is kind of crazy.

I think moving to node would make the code a lot more maintainable, and allow us to have much more meaningful error messages.

Please post any objections you may have here.

I will leave this issue open for about a week (Until September 24th at the earliest), before moving forward.

**Comment by AndreasWebdev** [comment]
+1 for a node rewrite. It would make this project seem much less "hacky" and could be integrated into other projects more easily (think about a ui-version for windows or similar)

**Comment by torch2424** [comment]
Thanks for the feedback @AndreasWebdev 😄 My only concern is that I noticed that a lot of new raspberry pi owners, or those who aren't day-to-day developers, often use this project. I feel like adding the step of installing node could be a bit of a pain for some. Especially if things like permissions get messed up.

I can suggest using something like nvm, but I feel like as long as the node version is LTS, then installing from apt-get should be fine.

**Comment by Nicholaiii** [comment]
I would join development if you switched to Node. I was considering writing it myself with some options for rendering in advance and such. 

Also, a +1 for nvm here, it's much nicer than apt, will work on any Linux distro and doesn't require su, because it installs in ~/.nvm.

**Comment by torch2424** [comment]
Awesome!

Yeah I'll start the node rewrite tonight, or tommorow. Would be awesome, to have some more contributors on the project as well :)

**Comment by AndreasWebdev** [comment]
I'd definitely be down at least studying the node code and potentially think of usecases for endusers!

**Comment by torch2424** [comment]
Rad!

Well I started this on the `node-rebuild` branch.

https://github.com/torch2424/piStreamRadio/tree/node-rebuild?files=1

I already made a project generator which is awesome and allows us to have more freedom in how we do things on the repo for things like upgradability. :)

**Comment by Nicholaiii** [comment]
I love the idea of a CLI that generates radio instances/configs and streams them as well. I was thinking to make a small web-gui? My idea is to keep it in a seperate repo that could be cloned, built and packaged into releases with the `prepare` script (that also allows you to do the same on local `npm install` during dev).

**Comment by torch2424** [comment]
@Nicholaiii 

Oh yes, I was definitely thinking about web interfaces as well! For the initial 2.0 I think I will get the original functionality that the bash project had. And then introduce a web ui in later revisions from contributions, or if I have the time.

@AndreasWebdev 

You make a good point as well! I think doing all of the config, files, and status should be hosted on the a port as an API. Then, any thing can simply hit that API to act as a frontend. We can offer a default front end as well with a flag if needed, that is hosted on a second port. 😄 If we start getting serious about multiple frontends, I'd suggest me make an org for this project.

**Comment by Nicholaiii** [comment]
I think rather than a flag, you could disable (or enable) a default web interface in the radio config file, and maybe even use a custom webpage to be hosted in the radio instance folder.

**Comment by AndreasWebdev** [comment]
I guess for the flexibility of the project the core library and any potential control systems should be seperate projects. This way people could simply use something like

`var stream = require('node-stream-radio');

var options = ['gif_folder': '/stream/gifs',
                       'music_folder': '/stream/music'];

stream.startStream(options);`

In any system they want. There could be a node-streamradio-desktop version with electron or node-streamradio-web with a simple web interface. If there would be an official web interface the setup/installer could ask if you want to use the cli only or the web interface.

**Comment by AndreasWebdev** [comment]
@torch2424 I'd be down for a potencial overlay project that hooks into this. It's actually something I tried out a few months back but decided to wait because handling this without a cross-plattform node-api turned out very messy!

**Comment by torch2424** [comment]
@Nicholaiii 

> I think rather than a flag, you could disable (or enable) a default web interface in the radio config file, and maybe even use a custom webpage to be hosted in the radio instance folder.

Actually I agree. Making the config file "git-able" will make maintaining the project much easier.

@AndreasWebdev 

> In any system they want. There could be a node-streamradio-desktop version with electron or node-streamradio-web with a simple web interface. If there would be an official web interface the setup/installer could ask if you want to use the cli only or the web interface.

I think we should steer towards just a CLI at this point. And that we expose a common endpoint API for these reasons. Like with the standard GET, and POST requests. Decoupling the project into a simple library, would mean we'd need two repos. `pi-stream-radio` vs. `pi-stream-radio-cli`. And would require a ton of different repos that install the main lib and it gets kinda funny, especially directing users to the right place. But if you can make a good point for this please do.

> I'd be down for a potential overlay project that hooks into this. It's actually something I tried out a few months back but decided to wait because handling this without a cross-plattform node-api turned out very messy!

Yeah totally haha! I made one at: https://github.com/torch2424/piStreamRadio-frontend but it only had a few set of features. If you want feel free to start commiting to this node project and expose some nice hooks on an api to edit the config file, and restart the project and things like that 😄

**Comment by Nicholaiii** [comment]
A definite +1 on keeping this a CLI. The userbase is largely comprised of non-developers and I think userfriendliness is a big advantage here. We're not looking to invent a streaming library but a way for people to easily use their hardware as a youtube streaming platform.

**Comment by AndreasWebdev** [comment]
Definitely what I meant. I was just thinking @Nicholaiii suggested implementing a frontend web interface into the main project which seems kinda messy, especially if you don't want to use a web interface but something different that hooks into the project. Kinda think of mysql, it can come bundled with phpmyadmin but if you will never use it, it might become a security risk and bloated to "just put it in there anyways because SOMEONE will use it".

Having a simple API is exactly what I think is what this project needs. If you want to implement it over an actual HTTP server like you said (at least that's what I got by GET and POST requests) it would actually work very similar to projects like shoutcast.

In the end, if you provide a way to reload the config, start/stop/restart the server, skip a song and get current song info I think we would have a featureset that is pretty potent for potential api-wrapper libraries.

**Comment by torch2424** [comment]
Seemed like more of a response to @Nicholaiii so I'll let them respond before chiming in.

But, 

> In the end, if you provide a way to reload the config, start/stop/restart the server, skip a song and get current song info I think we would have a featureset that is pretty potent for potential api-wrapper libraries.

I 100% Agree with. 😄 But if I could say, this will probably come after the 2.0.0 rewrite. Maybe in like a 2.1.0

**Comment by torch2424** [comment]
Also, any feeling about changing the project name?

I was thinking of putting it up on npm as `pi-stream-radio`. But I like how @AndreasWebdev mentioned `node-stream-radio`.

I want to keep the old name, just for SEO and finding the project. But since the technology is changing a bit, and I am trying to build this for desktop servers as well currently, renaming to `node-stream-radio` would make it seem like a more serious project, and we can probably save some confusion by adding a subtitle: *formerly known as piStreamRadio* ?

**Comment by Nicholaiii** [comment]
> Maybe as a middle ground you could ask the user in the initial configuration if they want to use a web frontend ui, kinda like how vue-webpack asks you if you want to use certain extra-features.

This is exactly what I was about to suggest before your edit! As an aside; I don't think "bloat" is an issue, if it has an API it already has the amount of "bloat" it takes to include hosting a web controlpanel. A simple vue project for example shouldn't be more 2-300kB with all vendor stuff included.

**Comment by Nicholaiii** [comment]
As for naming. Hm. I think the general consensus is that naming node packages `node-*` is a bit of a pleonasm (although keep in mind repo name =/= package name)
Definitely keep the name somewhere for SEO as mentioned, but a rename wouldn't be uncalled for.

**Comment by torch2424** [comment]
@Nicholaiii @AndreasWebdev 

So the only thing that I am worried about "Hey generate me a UI for my stream!" Is that what if they decide to do this step later on? And how do we handle updates for this UI that is built in the UI? I don't know the solution if we go with this approach, but I feel it is important to think about.

> As for naming. Hm. I think the general consensus is that naming node packages node-* is a bit of a pleonasm (although keep in mind repo name =/= package name)
Definitely keep the name somewhere for SEO as mentioned, but a rename wouldn't be uncalled for.

I agree `node-*` does seem a bit redundant. How about something like `livestream-radio` ?

**Comment by Nicholaiii** [comment]
Oh, I'm still in favour of including a UI in the main project, but just enabling/disabling it on a project-level basis. In this case, UI updates when the CLI does, and with a tool like [yeoman/update-notifier](https://github.com/yeoman/update-notifier) that's is a trivial task to notify endusers about.

**Comment by AndreasWebdev** [comment]
@torch2424 

> Also, any feeling about changing the project name?

It would make sense to name the project node-stream-radio and add the "formerly known" line like you said! It doesn't have to be named node-X but it should be clear that you can use the project with other systems that are not Raspberry Pi's

> Oh, I'm still in favour of including a UI in the main project, but just enabling/disabling it on a project-level basis.

In that case there could be a seperate webpanel repo that get's cloned if needed. This way webpanel and main system can get updated seperately.

**Comment by AndreasWebdev** [comment]
@torch2424 

> And how do we handle updates for this UI that is built in the UI?

Are you talking about a node-level api or a web-based api? On a node-level you could fire events that another app can listen on. On a web-based api you could use websockets or the web-api needs to continuously call an api endpoint.

**Comment by torch2424** [comment]
> Are you talking about a node-level api or a web-based api? On a node-level you could fire events that another app can listen on. On a web-based api you could use websockets or the web-api needs to continuously call an api endpoint.

Ooops, I meant more in the sense that, if we release a new version of this UI, how do we provide an upgrad path in our CLI, if we are going to generate out the UI?

**Comment by AndreasWebdev** [comment]
I guess it would make no sense like that in a node environment, would it?

From my experience, the UI should include the cli as a dependency. If the UI get's updated, it will have the required version of the cli in the package.json which will then get updated accordingly.

If the cli get's updated, the UI is not affected, because the UI is dependent on a certain version of the cli to not break functionality.

Maybe just adding any UI projects in the readme would be a better approach without overthinking a system for the cli to dynamically include addons. It should be as easy as installing the UI, which has the radio as a dependency. Especially for the usecase, that UI and radio-stream could be on different systems (stream on pi with a dedicated webserver or a frontend app for clients)

**Comment by torch2424** [comment]
Also, about halfway done with version `2.0.0` 😎 

<img width="629" alt="screen shot 2018-09-27 at 1 09 45 am" src="https://user-images.githubusercontent.com/1448289/46133088-89a0d500-c1f4-11e8-8249-40a9f2a660fe.png">
<img width="654" alt="screen shot 2018-09-27 at 1 26 59 am" src="https://user-images.githubusercontent.com/1448289/46133089-89a0d500-c1f4-11e8-95ba-672146660581.png">

**Comment by AndreasWebdev** [comment]
Very good! I guess once you'll ship 2.0.0 we could add issues specifically to the node-build, right? In any case I am eager to try it out!

**Comment by torch2424** [comment]
Yes exactly, after 2.0.0, feel free to open issues about any version 😄

**Comment by torch2424** [comment]
So, update from me:

Took a relaxing weekend, meaning I just worked on this. Got it all working with `.gif`, `.mp4`, and `.webm`! And it's more performant, I was able to get a 720p stream going on a pi 3! Though I am going to keep the default set to 420 

A lot less dependencies as well, only requires the additional `--enable-libfreetype` when building ffmpeg 👍, and the config.json is highly configurable.

Plan now is: Gonna just write that web API. Going to add some basic auth to the endpoints, where you define your users in the config.json. And then add some really basic endpoints. Going to do it in fastify, Because I feel like that would probably be the easiest way, as well as the most performant. And lastly, I'll write up the docs and deploy to npm! Hopefully have this done real soon! 😄

**Comment by torch2424** [comment]
Also, some other small things to do:

- Allow for an overlay image
- create an icon for the project using emojis, see emojione
- Add emojies to console.logs :)

**Comment by torch2424** [comment]
Added the overlay image, as well as some general Emoji stuff. Going to work on the API now.

**Comment by Nicholaiii** [comment]
Good work on the project so far! I started scaffolding API before the weekend but I've been so busy during I haven't had time to write anything back here. I'll send in a PR to let you know what's there and you can decide on where to go from that.

**Comment by Nicholaiii** [comment]
Nevermind that, I just saw you commit the api folder so too late again! 😆 Here's [a link to a 7z of it](https://drive.google.com/file/d/1qQN_Po21uj8kbF_Bvtp7n2wZ2qKJWCRS/view?usp=sharing)

**Comment by torch2424** [comment]
Oops sorry haha! I'll look over your API code later today, if not tommorow 👍 

I'll definitely try my best to implement what you have here, because I'm just lazily throwing together the API right now haha!

**Comment by torch2424** [comment]
@Nicholaiii I looked through your API Code, it was awesome!

Since you did it in koa there isn't much I can use there. But I agree JWTs would be good for giving auth to users. 

I was thinking of just encouraging users to store admins in the config.json, and checking passwords like that. Maybe even allowing to store basic auth style passwords for users?

**Comment by torch2424** [comment]
Ahhh that is what your were thinking? Yeah I was wondering why you added sockets haha! My initial API will all be HTTP requests, but feel free to open a PR for socket support 👍

**Comment by torch2424** [comment]
So Just finished the API. It's a simple HTTP REST JSON based api. And instead of doing proper "Authentication", I made it so that you define an api key in the config. That way for frontends going forward, can either ask you for your key when deploying a server side rendered frontend (the proper way), or just ask for the key when you enter the client, and have it stored in localstorage and used for all requests going forward (the easy way).

Also, my apologies, but the api is kinda hack-y and quickly written. Definitely want to move back to working on my emulator since there has been good interest in it lately, and put it on the backburner 👍

**Comment by torch2424** [comment]
Also @Nicholaiii I think we can definitely still use your code though as a server side rendered frontend. I am only exposing endpoints, while yours appeared to have proper user auth, and support for rendering HTML 😄
