### ISSUE TITLE
API: Return 405's instead of 404's when using wrong method

### ISSUE THREAD

**Issue by AndreasWebdev** [torch2424/live-stream-radio#66]
~~Appearently there seems to be a problem with sub-paths in the API. Calling /stream works on my end while /stream/restart results in an HTTP 404.~~

Maybe we should respond with an HTTP 405 when using GET on POST API calls and vice versa.

**Comment by AndreasWebdev** [comment]
Edit: /stream/restart is POST not GET, sorry it's getting late here. Maybe we could respond with a `405 - Method not allowed` for stupid people like me though

**Comment by torch2424** [comment]
Oh yeah I am totally for this! Feel free to get this in there since you are comfortable with the API 😄

**Comment by AndreasWebdev** [comment]
I'll get on it in around 8 hours when I wake up 😄

**Comment by torch2424** [comment]
Oh yeah no worries at all! You are already doing so much! No expectations on my end, just glad you are down to help with the project 😄

**Comment by AndreasWebdev** [comment]
And I am very happy to be part of this cool project! Your comments and everything really motivate me (you might've seen that ^^)
