### ISSUE TITLE
API: Changing config

### ISSUE THREAD

**Issue by AndreasWebdev** [torch2424/live-stream-radio#67]
Consider an API-call to update content in the config.json as clients might have no write-permission on an external ressource.

**Comment by torch2424** [comment]
Honestly, what we should be doing, is just re-requiring the config on every song. Which I'll go ahead and do now. Though in the future we should change this.

**Comment by AndreasWebdev** [comment]
Yes this also resolves another problem that you always have to restart the stream to see changes made to the config.

I thought we could maybe add a /config api-call with get and post methods to change the config.json through the api, as the stream might run on external hardware than the client accessing it. I can propose a PR tomorrow if you have nothing against that idea.

**Comment by torch2424** [comment]
Awesome glad we are in agreement 👍 

But yes, I am totally okay with a `/config` route, makes sense to me 😄
