### ISSUE TITLE
Minimal specs for a fluid 720p stream

### ISSUE THREAD

**Issue by AndreasWebdev** [torch2424/live-stream-radio#78]
As I mentioned, I want to run my radio through a hosted Ubuntu server. I currently struggle to find good specs.

Current server specs:
* Intel Xeon E5-2630 (2 Cores)
* 8GB DDR4 ram

Current config.json params:
* 480x320
* 2000k video_bitrate
* 30 fps
* 32 crf
* ultrafast preset

The stream works quite well, even on higher settings (1280x720 with superfast) but after around 30 seconds the YouTube dashboard tells me YouTube receives not enough video for a fluid stream. Would a switch to a server with more cores (my provider has a package with 4 and 8 cores) fix my issue or is it a different underlying problem?

**Comment by AndreasWebdev** [comment]
Changing some config.json params fixed the "YouTube receives not enough video" issue. However, the stream is still cutting off after a few seconds. YouTube then reports they get no stream data for a few seconds and then goes back to "Stream is good"..

Current config.json:
```
{
  [...]
  "audio_bit_rate": "128k",
  "video_height": "720",
  "video_width": "1280,
  "video_bit_rate": "3M",
  "video_fps": "30",
  "bufsize": "1M",
  "crf": "32",
  "preset": "ultrafast",
  "threads": 2
  [...]
}
```

**Comment by AndreasWebdev** [comment]
Upping the bufsize seems to make it better, however I don't think the buffer should be too big, I guess (the default config has it at 960k). So would a server with more cores have less issues?

**Comment by hyphmongo** [comment]
Maybe take a look at the CRF parameter?

I'm not sure if you can have a specific bitrate as well as a variable bitrate from the constant rate factor

**Comment by AndreasWebdev** [comment]
tbh. I've just copied the recommended settings from the Raspberry Pi page.

Edit: I've removed the crf setting and the problem persists. It seems to always work for ~35 seconds per song.

**Comment by torch2424** [comment]
Yeah I've been messing with performance myself. I made a huge performance update `2.1.1` last night, so maybe try that?

Also, Notice the threads option, you can set some of these to false to turn them off. I would perhaps try settings crf, bufsize, and threads to false so they don't get passed?

I am not entirely sure why this is happening. I noticed that my 2015 MBP at home could do even 1080 just fine. However, my raspberry pi started struggling with 360p 😢 , so I noticed a $5 digital ocean droplet works fine so I started using that.

Also, as a side note, can't test this as much anymore, Both of my youtube accounts got strikes (my personal one for "spamming", and the other for a copyright), because I had "Make livestream archive available", which then caused the strikes, so watch out for that haha! But I can still test on Twitch for short periods, and to local files to make sure things are working

Sorry for all the rambling, I know when I'm debugging random anecdotes help sometimes but yeah 😮

**Comment by AndreasWebdev** [comment]
Don't be sorry, your posts are helpful as always! 😄 Do I have to specifically set them to false? or could I just omit them?

**Comment by AndreasWebdev** [comment]
Oh and I am usually always running the current master branch cause it's easier to debug with it rather than installing the npm module.. I'd probably do that in a production environment though

**Comment by torch2424** [comment]
@AndreasWebdev You should be able to just omit them, the code for it is within this group of `if()` statements here:

https://github.com/torch2424/live-stream-radio/blob/master/src/stream/stream.js#L315

Also, was this before or after the `2.1.1` update? Perhaps moving video into its own input slowed things down? Or maybe it the audio normalization?

**Comment by AndreasWebdev** [comment]
That's super-odd! For the sake of testing (and finally having a 24/7 stream to play around with the api) I build myself a $5 droplet on digital ocean and set up the radio propertly with npm install -g live-stream-radio and all that.. this stream ALSO stops at 30 seconds, take a look at https://youtube.com/user/onestreamtests/live.

On my non-DO server, I have just cloned the repo @master directly to get the newest dev version and on the DO server I installed the latest nodejs production package..

**Comment by torch2424** [comment]
Yeah that's super weird. 

Last night I just installed the stream on one of my random droplets that Is a $5 one, and it streamed fine for like 5 different songs. Before my account got striked.

Perhaps try one of the builds from this: https://johnvansickle.com/ffmpeg/ That is what I used in my ffmpeg path for ubuntu and it worked fine 😮 

If that still is acting up, perhaps try playing with different Versions? Like on your master cloned DO, try going back at PRs, and checking out to commits before the PR to nail down what PR caused it?

**Comment by AndreasWebdev** [comment]
Alright, using the x86_64 build from https://johnvansickle.com/ffmpeg/ fixed it, so it's some sort of incompatiblity with the package manager ffmpeg version.

I just noticed that the version obtained by `apt install ffmpeg` is an older version!

Working version: 4.0.2-static
30s bug version: 3.4.4

**Comment by torch2424** [comment]
Ahhhhh! Awesome! That would make a ton of sense why the pi version is slow too then! 😄 

Let's go ahead and add this note in the README and the docs. Saying we suggest FFmpeg version >= 4.0.2 for a smooth stream 😄

**Comment by torch2424** [comment]
This means we should also make a new pi build of ffmpeg, and find a place to host it 😮 As I think it is bad practice to commit an FFmpeg build for only Pis on the repo, and force people to download it everytime it changes.

Let's just make a release as it is suggested by Github: https://help.github.com/articles/distributing-large-binaries/

And make it called "Pre-Compiled Tested FFmpeg Builds", and we can link to resources like the one above, as well as offer our own that users can contribute to 😄

**Comment by AndreasWebdev** [comment]
I have my stream up at https://www.youtube.com/channel/UCSAwpV80AFKopAJC0XAFWeA as a stability test!
