### ISSUE TITLE
Host some prebuilt FFmpeg

### ISSUE THREAD

**Issue by torch2424** [torch2424/live-stream-radio#83]
See #82 and #78 

Since we have specific FFmpeg version requirements, would be nice to build and offer FFmpeg for a few platforms, either provided by myself or other users, on a "Mock" release meant only for distributing builds of FFmpeg verified to work on `live-stream-radio`.

**Comment by torch2424** [comment]
Closed with: https://github.com/torch2424/live-stream-radio/releases/tag/ffmpeg-builds

**Comment by kylejbrk** [comment]
I am not seeing the binaries in that release.
