### ISSUE TITLE
Add lsr-wrapper to documentation

### ISSUE THREAD

**Issue by AndreasWebdev** [torch2424/live-stream-radio#86]
I believe you once said that you want to add projects building ontop of live-stream-radio to the documentation or something.

As I am working on LSRemote, I had to build a nice NodeJS wrapper for the API, so I decided to outsource this part as it's own npm module!

You can find the module [here](https://www.npmjs.com/package/lsr-wrapper) and the repo [here](https://github.com/LSRemote/lsr-wrapper)

**Comment by torch2424** [comment]
This is awesome! 🔥  

Yeah I'll add this to the docs tonight 👍 Great work! Super stoked on this haha! I like how you are building LSRemote so modular 😄

**Comment by AndreasWebdev** [comment]
I mean, whatever helps the main project should be donated to the mass 😄

**Comment by torch2424** [comment]
Yeah I 100% agree :)
