### ISSUE TITLE
Used a config.js vs a config.json for configuration

### ISSUE THREAD

**Issue by torch2424** [torch2424/live-stream-radio#87]
So I messed up, should have not coded this past midnight every night haha!

Just had a relvalation, how we can fix #80 and #48 

So I realized the config.json is getting kinda unweildy, and kind of reminds me of trying to figure out configs in OG webpack at this point. And thought it was already a downside of the project to have to manage this config. But it is git-able which is cool! But then I realized in things like rollup and webpack, I can dynamically run plugins and things whenever the app runs, and thought, we should do the same here!

Let's make a config.js with the following:

```js
module.exports = (streamStatusObjectCanAddKeysAndDocument) => {
// Do some cool stuff here

return aNewConfig
}
```

Essentially, let's just call a funciton whever we would `require(config.json)`, that way in the user's code, they can totally do things like time custom paths and all that, and we don't have to just keep making the config crazier and crazier 😄 

For an upgrade path, if there is no `config.js`, check for a `config.json`, and simply wrap it in a function that requires it 😄 

The `streamStatusObjectCanAddKeysAndDocument` is just an object. We can make it `{}` for now, but we can put things like the history object in there, and all that so users can react accoridngly 😄 

cc @AndreasWebdev what do you think?

**Comment by torch2424** [comment]
Actually, we can support both config.js, and config.json. Wouldn't be hard to do, and to maintain, just a single if block in the `index.js` 😄

**Comment by AndreasWebdev** [comment]
That's an odd thing I haven't seen, yet! how would such an config.js look like?

**Comment by torch2424** [comment]
Oh yeah, a lot of build tools will do this (which is where I got the idea). So for example, in animal crossing, lets assume we're doing 24 hour time

```js
// excuse the psuedo code
module.exports = (streamState) => {
const config = require('config.json')

const date = new Date();
const current_hour = date.getHours();
config.radio.video_directory = `/my/video/directory/${current_hour}`;

return config;
}
```

And this could return a different directory everytime the hour changes 😄

**Comment by torch2424** [comment]
Gonna code up this feature, feel free to say if you see any problems with this. It does add a level of "needing to know node", but I feel like the current config.json solves what most people are going to want. This would be more for people like you and me that want fine grain control of the stream to add our own cool features 😄

**Comment by AndreasWebdev** [comment]
I think the only problem I thought could occur is the extra step. If you fragment the config, people might get confused when to put stuff in the js and when to put it in the json.

However in your implementation it's more like a config.json override, you can define custom behavior to override config parameters. If we communicate this in the documentation, I think it could work.

**Comment by torch2424** [comment]
> I think the only problem I thought could occur is the extra step. If you fragment the config, people might get confused when to put stuff in the js and when to put it in the json.

@AndreasWebdev Yeah definitely, I'm not a fan of fragmenting things 😢 But I feel like this is kind of needed by anyone who may want to add their own "gimmick" to their stream, trying to maintain all of them down the line isn't scalable.

> However in your implementation it's more like a config.json override, you can define custom behavior to override config parameters. If we communicate this in the documentation, I think it could work.

Yes exactly! 😄 I did so in the docs, feel free to check them out in #88 I give an example of myself overriding, and mentioned overriding in another way 😄
