### ISSUE TITLE
UnhandledPromiseReject when using GIFs

### ISSUE THREAD

**Issue by Trobyss** [torch2424/live-stream-radio#93]
Hi !

Thanks a lot to have create this project ! It works perfectly !
But i have a little node error in my console :

![image](https://user-images.githubusercontent.com/43353685/46787971-58b6b900-cd39-11e8-8e6e-4e2e2df2b460.png)

![image](https://user-images.githubusercontent.com/43353685/46787475-ff01bf00-cd37-11e8-830a-280650f56c4c.png)

Thanks a lot !

Trobyss'

**Comment by torch2424** [comment]
Hello!

So it seems like something is going weird with .gifs , Can I suggest just not using gifs for now, they aren't the best for performance, and kept them in there more for legacy support 😄 Will deifnitely fix this once I have the time though.

And currently, I don't know enough FFMpeg to dynamically draw text mid song, but let's say you wanted to change the stream title in between songs, this can be done 😄 Find the "Dynamic Config" section in the [docs](https://torch2424.github.io/live-stream-radio/). I would link to it directly, but forgot the Github pages doesn't support SPA routing 😢 

Anyways, hope that helps in the meantime before we get this fixed 😄

**Comment by AndreasWebdev** [comment]
In that case, feel free to check out the npm package [lsr-wrapper](https://www.npmjs.com/package/lsr-wrapper), a simple wrapper for the api!

**Comment by AndreasWebdev** [comment]
@Trobyss did you manage to fix the issue on your end by not using gifs?

**Comment by djeraseit** [comment]
Yes gifs do not work out the box with this script using default generated assets.

`Playing the audio:
/var/www/youtubeStream/interludes/audio/nestedDirectoriesWork/tapeDeckSound.mp3

Finding/Optimizing video... ▒


(node:14235) UnhandledPromiseRejectionWarning: Error: Error in file: /tmp/live-stream-radio-gif-with-pal-1543340140217.gif

spawn /var/www/live-stream-radio/node_modules/gifsicle/vendor/gifsicle ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:14235) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function wit)
(node:14235) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will .
^C
root@kali:/var/www# file /tmp/live-stream-radio-gif-with-pal-1543340140217.gif
/tmp/live-stream-radio-gif-with-pal-1543340140217.gif: GIF image data, version 89a, 720 x 406
`

**Comment by djeraseit** [comment]
Ok I managed to fix this issue. `example 1.gif` file in interludes directory should be renamed so it does not have a space. Renaming to `example1.gif` works fine. This is probably due to the RFC rule that no spaces in url (it must be urlencoded).

**Comment by djeraseit** [comment]
**UPDATE** Removing .gif file throws this Warning

`Finding audio... 

Playing the audio:
/var/www/youtubeStream/interludes/audio/tapeDeckSound.mp3

Finding/Optimizing video... 

(node:14637) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'endsWith' of undefined
    at getVideo (/var/www/live-stream-radio/src/stream/stream.js:40:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:14637) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
`

**Comment by AndreasWebdev** [comment]
I would think that removing the gif leads to the interludes array being empty. You should disable the interludes if you don't have interlude-videos.
