### ISSUE TITLE
Problem of performance

### ISSUE THREAD

**Issue by Trobyss** [torch2424/live-stream-radio#99]
Hi ! with my raspberry, i have a big problems of perfromance... A music that lasts 3 minutes takes more than 10 minutes to be played. The stream is jerky...
Did u have an idea ? (The %CPU of ffmpeg is over 200% when i start)

Trob'

**Comment by AndreasWebdev** [comment]
Which raspberry pi model do you use? I think even my Pi3 has problems keeping up with a 720p stream so ffmpeg might just be too much for the CPU.

**Comment by Trobyss** [comment]
Oh okay...
3B V1.2

**Comment by AndreasWebdev** [comment]
You could try running the 1.X version of this project which has less overhead as it's made in bash rather than nodejs.

**Comment by torch2424** [comment]
Thanks @AndreasWebdev ! Everything they said haha!

That, or you can try reducing the output settings. And make sure you are running a recent version of FFmpeg, like greater than 4.0.0 😄

**Comment by torch2424** [comment]
Closing this as no more discussion 😄 Feel free to ask to re-open.
